name: Daily Discord Countdowns

on:
  schedule:
    # Été (CEST): 05:00 UTC = 07:00 Paris
    # Hiver (CET): 06:00 UTC = 07:00 Paris
    - cron: "0 5,6 * * *"
  # Permet de déclencher manuellement depuis l'onglet "Actions"
  workflow_dispatch:

jobs:
  send-countdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Librairies système nécessaires à CairoSVG
      - name: Install system libs for CairoSVG
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow tzdata cairosvg

      # Envoi automatique à 07:00 Europe/Paris,
      # et envoi forcé si déclenché manuellement (Run workflow)
      - name: Run at 07:00 Europe/Paris (or force on manual run)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FORCE_SEND: ${{ github.event_name == 'workflow_dispatch' && '1' || '0' }}
        run: |
          python - <<'PY'
          import os, datetime as dt
          from zoneinfo import ZoneInfo
          force = os.getenv("FORCE_SEND") == "1"
          now_paris = dt.datetime.now(ZoneInfo("Europe/Paris"))
          if not force and now_paris.hour != 7:
              print(f"[skip] Paris time is {now_paris:%H:%M}, not 07:00. Use Run workflow to force.")
              raise SystemExit(0)
          import countdown  # exécute l'envoi
          PY
