name: Daily Discord Countdowns

on:
  schedule:
    # Exécute tous les jours à 07:00 UTC
    # => 09:00 à Paris en été (CEST) / 08:00 en hiver (CET)
    - cron: "0 7 * * *"
  # Permet de lancer manuellement depuis l'onglet "Actions"
  workflow_dispatch:

jobs:
  send-countdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow

      - name: Send countdown image to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python countdown.py
