name: Daily Discord Countdowns

on:
  schedule:
    # Été (CEST): 05:00 UTC = 07:00 Paris
    # Hiver (CET): 06:00 UTC = 07:00 Paris
    - cron: "0 5,6 * * *"
  workflow_dispatch:

jobs:
  send-countdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow tzdata

      - name: Run at 07:00 Europe/Paris only
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python - <<'PY'
          import datetime as dt, os, sys, subprocess
          from zoneinfo import ZoneInfo
          now_paris = dt.datetime.now(ZoneInfo("Europe/Paris"))
          if now_paris.hour != 7:
              print(f"[skip] Paris time is {now_paris:%H:%M}, not 07:00.")
              sys.exit(0)
          import countdown  # exécute l'envoi si 07:00
          PY
